package Allenamento;

import Dashboard_Utente.Pannello_Utente;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class ScegliScheda extends javax.swing.JFrame {
    
    private SchedaCorso schedaCorso;
    private SchedaPersonalizzata schedaPersonalizzata;
    private String email;
    private String parte;
    private String giorni;
    private String giorniOre;
    private String mattina;
    private String pomeriggio;
    private String sera;
    private String kcal;
    private double fabbisogno;
    
    public ScegliScheda(String email, String parte, String giorni, String giorniOre, String mattina,String pomeriggio,String sera, String kcal, double fabbisogno ) {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/imageicon.png");
        setIconImage(icon.getImage());
        setTitle("GYM FOR YOU");
        this.email = email;
        this.parte = parte;
        this.giorni = giorni;
        this.giorniOre = giorniOre;
        this.mattina = mattina;
        this.pomeriggio = pomeriggio;
        this.sera = sera;
        this.kcal = kcal;
        this.fabbisogno = fabbisogno;
        
        combobox.setVisible(false);
        jLabel2.setVisible(false);
        comboboxtrainer.setVisible(false);
                
        
        schedaCorso = new SchedaCorso();
        Map dati = schedaCorso.prelevaCorsi();
        for (int i = 1; i < dati.size(); i++) {
            combobox.addItem((String)dati.get(""+i));
        }
        
        schedaPersonalizzata = new SchedaPersonalizzata();
        Map trainer = schedaPersonalizzata.prelevaTrainer();
        for (int i = 1; i < (trainer.size()/3)+1; i++) {
            String info = (String)trainer.get("email_"+i) + "/ "+ (String)trainer.get("nome_"+i) + "/ " + (String)trainer.get("cognome_"+i);
            comboboxtrainer.addItem(info );
        }
    }

    private ScegliScheda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        inviabottone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboboxtrainer = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 17, 30));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SCEGLI SCHEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 18), new java.awt.Color(255, 255, 102))); // NOI18N

        jRadioButton1.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 102));
        jRadioButton1.setText("Allenamento fatto da un nostro trainer");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 102));
        jRadioButton2.setText("Allenamento con corso");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        inviabottone.setBackground(new java.awt.Color(255, 255, 102));
        inviabottone.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        inviabottone.setText("INVIA");
        inviabottone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inviabottone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inviabottoneMouseClicked(evt);
            }
        });
        inviabottone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviabottoneActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indietro1.png"))); // NOI18N
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        combobox.setBackground(new java.awt.Color(255, 255, 102));
        combobox.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Scegli trainer che farà la scheda");

        comboboxtrainer.setBackground(new java.awt.Color(255, 255, 102));
        comboboxtrainer.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inviabottone, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox, 0, 269, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxtrainer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxtrainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inviabottone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void inviabottoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviabottoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inviabottoneActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        combobox.setVisible(true);
        jLabel2.setVisible(false);
        comboboxtrainer.setVisible(false);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        combobox.setVisible(false);
        jLabel2.setVisible(true);
        comboboxtrainer.setVisible(true);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        SceltaGiorni scelta = new SceltaGiorni(kcal, parte, giorni, fabbisogno);
        scelta.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void inviabottoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inviabottoneMouseClicked
        // TODO add your handling code here:
        String tipo;
        
        if (jRadioButton1.isSelected()) {
            schedaPersonalizzata = new SchedaPersonalizzata();
            tipo = "Scheda Personalizzata";
            String emailtrainer = (String) comboboxtrainer.getSelectedItem();
            String newString = emailtrainer.substring(0, emailtrainer.indexOf("/"));
            schedaPersonalizzata.inputUtenteTrainer(email, tipo, parte, giorniOre, mattina, pomeriggio, sera, kcal, newString, fabbisogno);

            Pannello_Utente pannello = new Pannello_Utente();
            pannello.setVisible(true);
            dispose();
        }else if(jRadioButton2.isSelected()){
            
            tipo = "" + combobox.getSelectedItem();
            schedaCorso = new SchedaCorso();
            String newString = schedaCorso.ottieniEmail(tipo);
            
            if (parte.contains("C") && tipo.equals("Boxe") || parte.contains("O") && tipo.equals("Boxe") || parte.contains("CO")&& tipo.equals("Boxe")) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Il corso che hai scelto non si addice alle parti del corpo che vuoi allenare\n Desideri andare avanti lo stesso?", "ATTENZIONE!", JOptionPane.YES_NO_OPTION);
                if(dialogResult == JOptionPane.YES_OPTION){
                    schedaCorso.inputUtenteTrainer(email, tipo, parte, giorniOre, mattina, pomeriggio, sera, kcal, newString, fabbisogno);
                    Pannello_Utente pannello = new Pannello_Utente();
                    pannello.setVisible(true);
                    dispose();
                }
                
            }else{
                schedaCorso.inputUtenteTrainer(email, tipo, parte, giorniOre, mattina, pomeriggio, sera, kcal, newString, fabbisogno);
                Pannello_Utente pannello = new Pannello_Utente();
                pannello.setVisible(true);
                dispose();
            }
            
            
            
            
        }       
        
        
    }//GEN-LAST:event_inviabottoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScegliScheda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScegliScheda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScegliScheda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScegliScheda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ScegliScheda().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JComboBox<String> comboboxtrainer;
    private javax.swing.JButton inviabottone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
