package Allenamento;

import Autenticazione.Utente;
import Dashboard_Utente.Pannello_Utente;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JRadioButtonMenuItem;

public class SceltaAllenamento extends javax.swing.JFrame {
    
    public SceltaAllenamento() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/imageicon.png");
        setIconImage(icon.getImage());
        setTitle("GYM FOR YOU");
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        /*
        Misure misure = new Misure();
        
        if (misure.getCosce_inter() == misure.getCosce_f()) {
            cosce.setVisible(false);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        petto = new javax.swing.JRadioButton();
        bicipiti = new javax.swing.JRadioButton();
        avambracci = new javax.swing.JRadioButton();
        cosce = new javax.swing.JRadioButton();
        polpacci = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lunedi = new javax.swing.JRadioButton();
        martedi = new javax.swing.JRadioButton();
        mercoledi = new javax.swing.JRadioButton();
        venerdi = new javax.swing.JRadioButton();
        sabato = new javax.swing.JRadioButton();
        domenica = new javax.swing.JRadioButton();
        dimagrimento = new javax.swing.JRadioButton();
        aumento = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        sedentario = new javax.swing.JRadioButton();
        pocoattivo = new javax.swing.JRadioButton();
        medioattivo = new javax.swing.JRadioButton();
        moltoattivo = new javax.swing.JRadioButton();
        estrattivo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pesodaperdere = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        anniallenamento = new javax.swing.JSpinner();
        avantibutton = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        giovedi = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 17, 30));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SCEGLI ALLENAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 18), new java.awt.Color(255, 255, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Parte del corpo");

        petto.setBackground(new java.awt.Color(155, 17, 30));
        petto.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        petto.setForeground(new java.awt.Color(255, 255, 102));
        petto.setText("Petto");
        petto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        petto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pettoActionPerformed(evt);
            }
        });

        bicipiti.setBackground(new java.awt.Color(155, 17, 30));
        bicipiti.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        bicipiti.setForeground(new java.awt.Color(255, 255, 102));
        bicipiti.setText("Bicipiti");
        bicipiti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        avambracci.setBackground(new java.awt.Color(155, 17, 30));
        avambracci.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        avambracci.setForeground(new java.awt.Color(255, 255, 102));
        avambracci.setText("Avambracci");
        avambracci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        avambracci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avambracciActionPerformed(evt);
            }
        });

        cosce.setBackground(new java.awt.Color(155, 17, 30));
        cosce.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        cosce.setForeground(new java.awt.Color(255, 255, 102));
        cosce.setText("Cosce");
        cosce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cosce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosceActionPerformed(evt);
            }
        });

        polpacci.setBackground(new java.awt.Color(155, 17, 30));
        polpacci.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        polpacci.setForeground(new java.awt.Color(255, 255, 102));
        polpacci.setText("Polpacci");
        polpacci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Modalità ");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Giorni");

        lunedi.setBackground(new java.awt.Color(155, 17, 30));
        lunedi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        lunedi.setForeground(new java.awt.Color(255, 255, 102));
        lunedi.setText("Lunedì");
        lunedi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        martedi.setBackground(new java.awt.Color(155, 17, 30));
        martedi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        martedi.setForeground(new java.awt.Color(255, 255, 102));
        martedi.setText("Martedì");
        martedi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mercoledi.setBackground(new java.awt.Color(155, 17, 30));
        mercoledi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        mercoledi.setForeground(new java.awt.Color(255, 255, 102));
        mercoledi.setText("Mercoledì");
        mercoledi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        venerdi.setBackground(new java.awt.Color(155, 17, 30));
        venerdi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        venerdi.setForeground(new java.awt.Color(255, 255, 102));
        venerdi.setText("Venerdì");
        venerdi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        venerdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venerdiActionPerformed(evt);
            }
        });

        sabato.setBackground(new java.awt.Color(155, 17, 30));
        sabato.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        sabato.setForeground(new java.awt.Color(255, 255, 102));
        sabato.setText("Sabato");
        sabato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        domenica.setBackground(new java.awt.Color(155, 17, 30));
        domenica.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        domenica.setForeground(new java.awt.Color(255, 255, 102));
        domenica.setText("Domenica");
        domenica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        dimagrimento.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup2.add(dimagrimento);
        dimagrimento.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        dimagrimento.setForeground(new java.awt.Color(255, 255, 102));
        dimagrimento.setText("Dimagrisici");
        dimagrimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dimagrimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dimagrimentoMouseClicked(evt);
            }
        });

        aumento.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup2.add(aumento);
        aumento.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        aumento.setForeground(new java.awt.Color(255, 255, 102));
        aumento.setText("Aumenta");
        aumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aumentoMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(155, 17, 30));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        sedentario.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup3.add(sedentario);
        sedentario.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        sedentario.setForeground(new java.awt.Color(255, 255, 102));
        sedentario.setText("Sedentario");
        sedentario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pocoattivo.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup3.add(pocoattivo);
        pocoattivo.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        pocoattivo.setForeground(new java.awt.Color(255, 255, 102));
        pocoattivo.setText("Poco attivo");
        pocoattivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        medioattivo.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup3.add(medioattivo);
        medioattivo.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        medioattivo.setForeground(new java.awt.Color(255, 255, 102));
        medioattivo.setText("Mediamente attivo");
        medioattivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        moltoattivo.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup3.add(moltoattivo);
        moltoattivo.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        moltoattivo.setForeground(new java.awt.Color(255, 255, 102));
        moltoattivo.setText("Molto attivo");
        moltoattivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        estrattivo.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup3.add(estrattivo);
        estrattivo.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        estrattivo.setForeground(new java.awt.Color(255, 255, 102));
        estrattivo.setText("Estremamente attivo ");
        estrattivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sedentario)
                    .addComponent(pocoattivo)
                    .addComponent(medioattivo)
                    .addComponent(moltoattivo)
                    .addComponent(estrattivo))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sedentario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pocoattivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medioattivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moltoattivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(estrattivo)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(155, 17, 30));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Pesso che vuoi perdere a settimana :");

        pesodaperdere.setBackground(new java.awt.Color(155, 17, 30));
        pesodaperdere.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        pesodaperdere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesodaperdereActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("g");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pesodaperdere, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesodaperdere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(155, 17, 30));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText(" Anni di allenamento : ");

        anniallenamento.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(anniallenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anniallenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        avantibutton.setBackground(new java.awt.Color(255, 255, 102));
        avantibutton.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        avantibutton.setText("AVANTI");
        avantibutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        avantibutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avantibuttonMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indietro1.png"))); // NOI18N
        jLabel6.setText("BACK");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        giovedi.setBackground(new java.awt.Color(155, 17, 30));
        giovedi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        giovedi.setForeground(new java.awt.Color(255, 255, 102));
        giovedi.setText("Giovedì");
        giovedi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(petto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dimagrimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lunedi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(martedi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mercoledi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(giovedi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bicipiti)
                                .addGap(30, 30, 30)
                                .addComponent(avambracci)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(cosce)
                                .addGap(57, 57, 57)
                                .addComponent(polpacci, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(avantibutton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(venerdi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sabato, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(domenica)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(petto)
                    .addComponent(bicipiti)
                    .addComponent(avambracci)
                    .addComponent(polpacci)
                    .addComponent(cosce))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dimagrimento))
                        .addGap(18, 18, 18)
                        .addComponent(aumento))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunedi)
                    .addComponent(martedi)
                    .addComponent(mercoledi)
                    .addComponent(venerdi)
                    .addComponent(sabato)
                    .addComponent(domenica)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giovedi))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avantibutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pettoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pettoActionPerformed

    private void cosceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cosceActionPerformed

    private void venerdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venerdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venerdiActionPerformed

    private void avantibuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avantibuttonMouseClicked
        // TODO add your handling code here:
       
        SceltaGiorni momento;//E IL FRAME
        Utente utente = new Utente();
        
        if(petto.isSelected() || bicipiti.isSelected() || avambracci.isSelected() || cosce.isSelected() || polpacci.isSelected()){
            if (dimagrimento.isSelected() || aumento.isSelected()) {
                if (sedentario.isSelected() || pocoattivo.isSelected()|| medioattivo.isSelected() || moltoattivo.isSelected() || estrattivo.isSelected()) {
                    if (lunedi.isSelected() || martedi.isSelected() || mercoledi.isSelected() || giovedi.isSelected() || venerdi.isSelected() || sabato.isSelected() || domenica.isSelected()) {

                        double massa = utente.getMassamagra();
                        double[] percentuale = {1.2, 1.375, 1.55, 1.725, 1.9};
                        double mbr = 370 + (21.6 * massa);
                        double tee= 0;

                        JRadioButton[] stileVita = new JRadioButton[]{sedentario, pocoattivo, medioattivo, moltoattivo, estrattivo};

                        for (int i = 0; i < stileVita.length; i++) {
                            if (stileVita[i].isSelected()) {
                                tee = mbr * percentuale[i];
                            }
                        }

                        JRadioButton[] jradio = new JRadioButton[]{petto, avambracci, bicipiti, cosce, polpacci};
                        String[] inizialiPartiCorpo = new String[]{"P","A","B","C","O"};
                        String parte = "";

                        for (int i = 0; i < jradio.length; i++) {
                            if (jradio[i].isSelected()) {
                                parte+=inizialiPartiCorpo[i];
                            }
                        }

                        String giorni = "";
                        JRadioButton[] jradio1 = new JRadioButton[]{lunedi,martedi,mercoledi,giovedi,venerdi,sabato,domenica};
                        String[] inizialigiorni = new String[]{"L","M","W","G","V","S","D"};

                        for (int i = 0; i < jradio1.length; i++) {
                            if (jradio1[i].isSelected()) {
                                giorni+=inizialigiorni[i];
                            }
                        }
                        double risultato;
                        double fabbisogno;

                        if (dimagrimento.isSelected()) {
                            
                            if (!pesodaperdere.getText().isEmpty()) {
                                double pesodaPerd = Double.parseDouble(pesodaperdere.getText());
                                if(pesodaPerd < 1000.0 ){
                                    if( utente.getAltezza() > 150 && utente.getAltezza() <= 179  && utente.getPeso() > 50 && utente.getPeso() <=79 && pesodaPerd <400 ){
                                        String[] str = pesodaperdere.getText().split("");
                                        int conta = 0;

                                        for (String str1 : str) {
                                            if (!str1.matches("\\d+")) {
                                                conta+=1;
                                            }
                                        }
                                        if(conta==0){
                                            double pesoDaPerdere = (Double.parseDouble(pesodaperdere.getText()))/450;
                                            risultato = Math.round(500 * pesoDaPerdere);
                                            fabbisogno = Math.round(tee);

                                            String kcal = String.valueOf(risultato);
                                            momento = new SceltaGiorni(kcal, parte, giorni, fabbisogno);
                                            momento.setVisible(true);
                                            dispose();
                                        }else{
                                            JOptionPane.showMessageDialog(null, "Caratteri inseriti male", "Attenzione!", JOptionPane.WARNING_MESSAGE);
                                            pesodaperdere.setText("");
                                        }
                                    }else{
                                        JOptionPane.showConfirmDialog(null, "I grammi inseriti sono troppo alti per la tua corporatura\n Diminuire i grammi e riprovare", "ATTENZIONE!", JOptionPane.WARNING_MESSAGE);
                                    }
                                }else{
                                    JOptionPane.showConfirmDialog(null, "I grammi inseriti sono troppo alti.\n Diminuire i grammi e riprovare", "ATTENZIONE!", JOptionPane.WARNING_MESSAGE);
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "Inserire il peso da perdere!", "Attenzione!", JOptionPane.WARNING_MESSAGE);
                            }

                        }else if(aumento.isSelected()){

                            double polso = utente.getPolso() /2.54;
                            double guadagno = 0.3 * Math.pow(polso, 2) * Math.pow(0.5, ((Integer)anniallenamento.getValue()-1));
                            double guadagnoSettimana = guadagno/52;
                            double kcalSettimana = (3500 * guadagnoSettimana) /1;
                            risultato = Math.round(kcalSettimana/7);
                            fabbisogno = Math.round(tee + risultato + risultato);

                            String kcal = String.valueOf(risultato);
                            momento = new SceltaGiorni(kcal, parte, giorni, fabbisogno);
                            momento.setVisible(true);
                            dispose();
                        }

                    }else{
                        JOptionPane.showMessageDialog(null, "Selezionare uno o più giorni di allenamento!", "Attenzione!", JOptionPane.WARNING_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Selezionare uno stile di vita!", "Attenzione!", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Selezionare una modalità di allenamento!", "Attenzione!", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selezionare una o più parti del corpo da allenare", "Attenzione!", JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_avantibuttonMouseClicked

    private void dimagrimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dimagrimentoMouseClicked
        // TODO add your handling code here:
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
    }//GEN-LAST:event_dimagrimentoMouseClicked

    private void pesodaperdereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesodaperdereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesodaperdereActionPerformed

    private void aumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aumentoMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        jPanel3.setVisible(false);

    }//GEN-LAST:event_aumentoMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Pannello_Utente pannello = new Pannello_Utente();
        pannello.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void avambracciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avambracciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avambracciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SceltaAllenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SceltaAllenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SceltaAllenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SceltaAllenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SceltaAllenamento().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner anniallenamento;
    private javax.swing.JRadioButton aumento;
    private javax.swing.JRadioButton avambracci;
    private javax.swing.JToggleButton avantibutton;
    private javax.swing.JRadioButton bicipiti;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton cosce;
    private javax.swing.JRadioButton dimagrimento;
    private javax.swing.JRadioButton domenica;
    private javax.swing.JRadioButton estrattivo;
    private javax.swing.JRadioButton giovedi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton lunedi;
    private javax.swing.JRadioButton martedi;
    private javax.swing.JRadioButton medioattivo;
    private javax.swing.JRadioButton mercoledi;
    private javax.swing.JRadioButton moltoattivo;
    private javax.swing.JTextField pesodaperdere;
    private javax.swing.JRadioButton petto;
    private javax.swing.JRadioButton pocoattivo;
    private javax.swing.JRadioButton polpacci;
    private javax.swing.JRadioButton sabato;
    private javax.swing.JRadioButton sedentario;
    private javax.swing.JRadioButton venerdi;
    // End of variables declaration//GEN-END:variables
}
