package Allenamento;

import Autenticazione.Utente;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;


public class SceltaGiorni extends javax.swing.JFrame {

    private String parte, giorni;  
    private String kcal;
    private double fabbisogno;
  
    public SceltaGiorni(String kcal, String parte, String giorni, double fabbisogno) {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/imageicon.png");
        setIconImage(icon.getImage());
        setTitle("GYM FOR YOU");
        this.kcal = kcal;
        this.parte = parte;
        this.giorni = giorni;
        this.fabbisogno = fabbisogno;
        
        if (!giorni.contains("L")) {
            lunedi.setVisible(false);
            JRadioButton[] jradio = new JRadioButton[]{lm,lp,ls };
            for (JRadioButton l : jradio) { l.setVisible(false); }
            JComboBox[] jcombo = new JComboBox[]{l1,l2,l3};
            for (JComboBox l : jcombo) { l.setVisible(false); }
        }
        if (!giorni.contains("L")) {
            lunedi.setVisible(false);
            JRadioButton[] jradio = new JRadioButton[]{lm,lp,ls };
            for (JRadioButton l : jradio) { l.setVisible(false); }
            JComboBox[] jcombo = new JComboBox[]{l1,l2,l3};
            for (JComboBox l : jcombo) { l.setVisible(false); }
        }
        if (!giorni.contains("M")) {
            martedi.setVisible(false);
            JRadioButton[] jradio = new JRadioButton[]{mm,mp,ms };
            for (JRadioButton m : jradio) { m.setVisible(false); }
            JComboBox[] jcombo = new JComboBox[]{m1,m2,m3};
            for (JComboBox m : jcombo) { m.setVisible(false); }
        }
        if (!giorni.contains("W")) {
            mercoledi.setVisible(false);
            JRadioButton[] jradio = new JRadioButton[]{wm,wp,ws };
            for (JRadioButton w : jradio) { w.setVisible(false); }
            JComboBox[] jcombo = new JComboBox[]{w1,w2,w3};
            for (JComboBox w : jcombo) { w.setVisible(false); }
        }
        if (!giorni.contains("G")) {
            giovedi.setVisible(false);
            JRadioButton[] jradio = new JRadioButton[]{gm,gp,gs };
            for (JRadioButton g : jradio) { g.setVisible(false); }
            JComboBox[] jcombo = new JComboBox[]{g1,g2,g3};
            for (JComboBox g : jcombo) { g.setVisible(false); }
        }
        if (!giorni.contains("V")) {
            venerdi.setVisible(false);
            JRadioButton[] jradio = new JRadioButton[]{vm,vp,vs };
            for (JRadioButton v : jradio) { v.setVisible(false); }
            JComboBox[] jcombo = new JComboBox[]{v1,v2,v3};
            for (JComboBox v : jcombo) { v.setVisible(false); }
        }
        if (!giorni.contains("S")) {
            sabato.setVisible(false);
            JRadioButton[] jradio = new JRadioButton[]{sm,sp,ss };
            for (JRadioButton s : jradio) { s.setVisible(false); }
            JComboBox[] jcombo = new JComboBox[]{s1,s2,s3};
            for (JComboBox s : jcombo) { s.setVisible(false); }
        }
        if (!giorni.contains("D")) {
            domenica.setVisible(false);
            JRadioButton[] jradio = new JRadioButton[]{dm,dp,ds };
            for (JRadioButton d : jradio) { d.setVisible(false); }
            JComboBox[] jcombo = new JComboBox[]{d1,d2,d3};
            for (JComboBox d : jcombo) { d.setVisible(false); }
        }
    }

    private SceltaGiorni() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        martedi = new javax.swing.JLabel();
        lm = new javax.swing.JRadioButton();
        lp = new javax.swing.JRadioButton();
        ls = new javax.swing.JRadioButton();
        l1 = new javax.swing.JComboBox<>();
        l3 = new javax.swing.JComboBox<>();
        l2 = new javax.swing.JComboBox<>();
        lunedi = new javax.swing.JLabel();
        mm = new javax.swing.JRadioButton();
        m1 = new javax.swing.JComboBox<>();
        mp = new javax.swing.JRadioButton();
        m2 = new javax.swing.JComboBox<>();
        ms = new javax.swing.JRadioButton();
        m3 = new javax.swing.JComboBox<>();
        mercoledi = new javax.swing.JLabel();
        wm = new javax.swing.JRadioButton();
        w1 = new javax.swing.JComboBox<>();
        wp = new javax.swing.JRadioButton();
        w2 = new javax.swing.JComboBox<>();
        ws = new javax.swing.JRadioButton();
        w3 = new javax.swing.JComboBox<>();
        giovedi = new javax.swing.JLabel();
        gm = new javax.swing.JRadioButton();
        g1 = new javax.swing.JComboBox<>();
        gp = new javax.swing.JRadioButton();
        g2 = new javax.swing.JComboBox<>();
        gs = new javax.swing.JRadioButton();
        g3 = new javax.swing.JComboBox<>();
        venerdi = new javax.swing.JLabel();
        vm = new javax.swing.JRadioButton();
        v1 = new javax.swing.JComboBox<>();
        vp = new javax.swing.JRadioButton();
        v2 = new javax.swing.JComboBox<>();
        vs = new javax.swing.JRadioButton();
        v3 = new javax.swing.JComboBox<>();
        sabato = new javax.swing.JLabel();
        sm = new javax.swing.JRadioButton();
        s1 = new javax.swing.JComboBox<>();
        sp = new javax.swing.JRadioButton();
        s2 = new javax.swing.JComboBox<>();
        ss = new javax.swing.JRadioButton();
        s3 = new javax.swing.JComboBox<>();
        domenica = new javax.swing.JLabel();
        dm = new javax.swing.JRadioButton();
        d1 = new javax.swing.JComboBox<>();
        dp = new javax.swing.JRadioButton();
        d2 = new javax.swing.JComboBox<>();
        ds = new javax.swing.JRadioButton();
        d3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 17, 30));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SCEGLI ALLENAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 18), new java.awt.Color(255, 255, 102))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(799, 590));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 102));
        jToggleButton1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jToggleButton1.setText("INVIA");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indietro1.png"))); // NOI18N
        jLabel6.setText("BACK");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        martedi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        martedi.setForeground(new java.awt.Color(255, 255, 102));
        martedi.setText("Martedì");

        lm.setBackground(new java.awt.Color(155, 17, 30));
        lm.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        lm.setForeground(new java.awt.Color(255, 255, 102));
        lm.setText("Mattina");
        lm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lp.setBackground(new java.awt.Color(155, 17, 30));
        lp.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        lp.setForeground(new java.awt.Color(255, 255, 102));
        lp.setText("Pomeriggio");
        lp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpActionPerformed(evt);
            }
        });

        ls.setBackground(new java.awt.Color(155, 17, 30));
        ls.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        ls.setForeground(new java.awt.Color(255, 255, 102));
        ls.setText("Sera");
        ls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsActionPerformed(evt);
            }
        });

        l1.setBackground(new java.awt.Color(255, 255, 102));
        l1.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        l1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        l3.setBackground(new java.awt.Color(255, 255, 102));
        l3.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        l3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));
        l3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3ActionPerformed(evt);
            }
        });

        l2.setBackground(new java.awt.Color(255, 255, 102));
        l2.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        l2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        lunedi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        lunedi.setForeground(new java.awt.Color(255, 255, 102));
        lunedi.setText("Lunedì");

        mm.setBackground(new java.awt.Color(155, 17, 30));
        mm.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        mm.setForeground(new java.awt.Color(255, 255, 102));
        mm.setText("Mattina");
        mm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        m1.setBackground(new java.awt.Color(255, 255, 102));
        m1.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        m1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        mp.setBackground(new java.awt.Color(155, 17, 30));
        mp.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        mp.setForeground(new java.awt.Color(255, 255, 102));
        mp.setText("Pomeriggio");
        mp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpActionPerformed(evt);
            }
        });

        m2.setBackground(new java.awt.Color(255, 255, 102));
        m2.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        m2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        ms.setBackground(new java.awt.Color(155, 17, 30));
        ms.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        ms.setForeground(new java.awt.Color(255, 255, 102));
        ms.setText("Sera");
        ms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });

        m3.setBackground(new java.awt.Color(255, 255, 102));
        m3.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        m3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });

        mercoledi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        mercoledi.setForeground(new java.awt.Color(255, 255, 102));
        mercoledi.setText("Mercoledì");

        wm.setBackground(new java.awt.Color(155, 17, 30));
        wm.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        wm.setForeground(new java.awt.Color(255, 255, 102));
        wm.setText("Mattina");
        wm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        w1.setBackground(new java.awt.Color(255, 255, 102));
        w1.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        w1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        wp.setBackground(new java.awt.Color(155, 17, 30));
        wp.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        wp.setForeground(new java.awt.Color(255, 255, 102));
        wp.setText("Pomeriggio");
        wp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpActionPerformed(evt);
            }
        });

        w2.setBackground(new java.awt.Color(255, 255, 102));
        w2.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        w2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        ws.setBackground(new java.awt.Color(155, 17, 30));
        ws.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        ws.setForeground(new java.awt.Color(255, 255, 102));
        ws.setText("Sera");
        ws.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsActionPerformed(evt);
            }
        });

        w3.setBackground(new java.awt.Color(255, 255, 102));
        w3.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        w3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));
        w3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w3ActionPerformed(evt);
            }
        });

        giovedi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        giovedi.setForeground(new java.awt.Color(255, 255, 102));
        giovedi.setText("Giovedì");

        gm.setBackground(new java.awt.Color(155, 17, 30));
        gm.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        gm.setForeground(new java.awt.Color(255, 255, 102));
        gm.setText("Mattina");
        gm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        g1.setBackground(new java.awt.Color(255, 255, 102));
        g1.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        g1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        gp.setBackground(new java.awt.Color(155, 17, 30));
        gp.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        gp.setForeground(new java.awt.Color(255, 255, 102));
        gp.setText("Pomeriggio");
        gp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpActionPerformed(evt);
            }
        });

        g2.setBackground(new java.awt.Color(255, 255, 102));
        g2.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        g2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        gs.setBackground(new java.awt.Color(155, 17, 30));
        gs.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        gs.setForeground(new java.awt.Color(255, 255, 102));
        gs.setText("Sera");
        gs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsActionPerformed(evt);
            }
        });

        g3.setBackground(new java.awt.Color(255, 255, 102));
        g3.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        g3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));
        g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g3ActionPerformed(evt);
            }
        });

        venerdi.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        venerdi.setForeground(new java.awt.Color(255, 255, 102));
        venerdi.setText("Venerdì");

        vm.setBackground(new java.awt.Color(155, 17, 30));
        vm.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        vm.setForeground(new java.awt.Color(255, 255, 102));
        vm.setText("Mattina");
        vm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        v1.setBackground(new java.awt.Color(255, 255, 102));
        v1.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        v1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        vp.setBackground(new java.awt.Color(155, 17, 30));
        vp.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        vp.setForeground(new java.awt.Color(255, 255, 102));
        vp.setText("Pomeriggio");
        vp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vpActionPerformed(evt);
            }
        });

        v2.setBackground(new java.awt.Color(255, 255, 102));
        v2.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        v2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        vs.setBackground(new java.awt.Color(155, 17, 30));
        vs.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        vs.setForeground(new java.awt.Color(255, 255, 102));
        vs.setText("Sera");
        vs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsActionPerformed(evt);
            }
        });

        v3.setBackground(new java.awt.Color(255, 255, 102));
        v3.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        v3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));
        v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v3ActionPerformed(evt);
            }
        });

        sabato.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        sabato.setForeground(new java.awt.Color(255, 255, 102));
        sabato.setText("Sabato");

        sm.setBackground(new java.awt.Color(155, 17, 30));
        sm.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        sm.setForeground(new java.awt.Color(255, 255, 102));
        sm.setText("Mattina");
        sm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s1.setBackground(new java.awt.Color(255, 255, 102));
        s1.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        sp.setBackground(new java.awt.Color(155, 17, 30));
        sp.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        sp.setForeground(new java.awt.Color(255, 255, 102));
        sp.setText("Pomeriggio");
        sp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });

        s2.setBackground(new java.awt.Color(255, 255, 102));
        s2.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        s2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        ss.setBackground(new java.awt.Color(155, 17, 30));
        ss.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        ss.setForeground(new java.awt.Color(255, 255, 102));
        ss.setText("Sera");
        ss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssActionPerformed(evt);
            }
        });

        s3.setBackground(new java.awt.Color(255, 255, 102));
        s3.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        s3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        domenica.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        domenica.setForeground(new java.awt.Color(255, 255, 102));
        domenica.setText("Domenica");

        dm.setBackground(new java.awt.Color(155, 17, 30));
        dm.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        dm.setForeground(new java.awt.Color(255, 255, 102));
        dm.setText("Mattina");
        dm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d1.setBackground(new java.awt.Color(255, 255, 102));
        d1.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        d1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        dp.setBackground(new java.awt.Color(155, 17, 30));
        dp.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        dp.setForeground(new java.awt.Color(255, 255, 102));
        dp.setText("Pomeriggio");
        dp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpActionPerformed(evt);
            }
        });

        d2.setBackground(new java.awt.Color(255, 255, 102));
        d2.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        d2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));

        ds.setBackground(new java.awt.Color(155, 17, 30));
        ds.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        ds.setForeground(new java.awt.Color(255, 255, 102));
        ds.setText("Sera");
        ds.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsActionPerformed(evt);
            }
        });

        d3.setBackground(new java.awt.Color(255, 255, 102));
        d3.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        d3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leggero", "Medio", "Pesante" }));
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(giovedi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gs, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(venerdi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(85, 85, 85)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sabato, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(domenica, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(85, 85, 85)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ds, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 252, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(martedi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lunedi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ls, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mercoledi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ws, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lm)
                    .addComponent(lp)
                    .addComponent(ls)
                    .addComponent(lunedi))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(martedi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mm)
                            .addComponent(mp)
                            .addComponent(ms))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mercoledi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wm)
                            .addComponent(wp)
                            .addComponent(ws))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(w1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giovedi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gm)
                            .addComponent(gp)
                            .addComponent(gs))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(venerdi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vm)
                            .addComponent(vp)
                            .addComponent(vs))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sabato)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sm)
                            .addComponent(sp)
                            .addComponent(ss))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(domenica)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dm)
                            .addComponent(dp)
                            .addComponent(ds))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lsActionPerformed

    private void lpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lpActionPerformed

    private void l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l3ActionPerformed

    private void mpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpActionPerformed

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m3ActionPerformed

    private void wpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wpActionPerformed

    private void wsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wsActionPerformed

    private void w3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w3ActionPerformed

    private void gpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpActionPerformed

    private void gsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gsActionPerformed

    private void g3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g3ActionPerformed

    private void vpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vpActionPerformed

    private void vsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vsActionPerformed

    private void v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v3ActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spActionPerformed

    private void ssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s3ActionPerformed

    private void dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpActionPerformed

    private void dsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d3ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        
        String mattina = "";
        String pomeriggio = "";
        String sera = "";
        
        //*********************************************************************** LUNEDI'
        if (giorni.contains("L")) {
            // MATTINA
            if (lm.isSelected()) {
                if (l1.getSelectedItem().equals("Leggero")) {
                    mattina+="LL";
                }else if(l1.getSelectedItem().equals("Medio")){
                    mattina+="LM";
                }else if(l1.getSelectedItem().equals("Pesante")){
                    mattina+="LP";
                }
            }
            // POMERIGGIO
            if (lp.isSelected()) {
                if (l2.getSelectedItem().equals("Leggero")) {
                    pomeriggio+="LL";
                }else if(l2.getSelectedItem().equals("Medio")){
                    pomeriggio+="LM";
                }else if(l2.getSelectedItem().equals("Pesante")){
                    pomeriggio+="LP";
                }
            }
            // SERA
            if (ls.isSelected()) {
                if (l3.getSelectedItem().equals("Leggero")) {
                    sera+="LL";
                }else if(l3.getSelectedItem().equals("Medio")){
                    sera+="LM";
                }else if(l3.getSelectedItem().equals("Pesante")){
                    sera+="LP";
                }
            }
        }
        //*********************************************************************** MARTEDI'
        if (giorni.contains("M")) {
        // MATTINA
            if (mm.isSelected()) {
                if (m1.getSelectedItem().equals("Leggero")) {
                    mattina+="ML";
                }else if(m1.getSelectedItem().equals("Medio")){
                    mattina+="MM";
                }else if(m1.getSelectedItem().equals("Pesante")){
                    mattina+="MP";
                }
            }
            // POMERIGGIO
            if (mp.isSelected()) {
                if (m2.getSelectedItem().equals("Leggero")) {
                    pomeriggio+="ML";
                }else if(m2.getSelectedItem().equals("Medio")){
                    pomeriggio+="MM";
                }else if(m2.getSelectedItem().equals("Pesante")){
                    pomeriggio+="MP";
                }
            }
            // SERA
            if (ms.isSelected()) {
                if (m3.getSelectedItem().equals("Leggero")) {
                    sera+="ML";
                }else if(m3.getSelectedItem().equals("Medio")){
                    sera+="MM";
                }else if(m3.getSelectedItem().equals("Pesante")){
                    sera+="MP";
                }
            }
        }
        //*********************************************************************** MERCOLEDI'
        if (giorni.contains("W")) {
            // MATTINA
            if (wm.isSelected()) {
                if (w1.getSelectedItem().equals("Leggero")) {
                    mattina+="WL";
                }else if(w1.getSelectedItem().equals("Medio")){
                    mattina+="WM";
                }else if(w1.getSelectedItem().equals("Pesante")){
                    mattina+="WP";
                }
            }
            // POMERIGGIO
            if (wp.isSelected()) {
                if (w2.getSelectedItem().equals("Leggero")) {
                    pomeriggio+="WL";
                }else if(w2.getSelectedItem().equals("Medio")){
                    pomeriggio+="WM";
                }else if(w2.getSelectedItem().equals("Pesante")){
                    pomeriggio+="WP";
                }
            }
            // SERA
            if (ws.isSelected()) {
                if (w3.getSelectedItem().equals("Leggero")) {
                    sera+="WL";
                }else if(w3.getSelectedItem().equals("Medio")){
                    sera+="WM";
                }else if(w3.getSelectedItem().equals("Pesante")){
                    sera+="WP";
                }
            }
        }
        //*********************************************************************** GIOVEDI'
        if (giorni.contains("G")) {
        // MATTINA
            if (gm.isSelected()) {
                if (g1.getSelectedItem().equals("Leggero")) {
                    mattina+="GL";
                }else if(g1.getSelectedItem().equals("Medio")){
                    mattina+="GM";
                }else if(g1.getSelectedItem().equals("Pesante")){
                    mattina+="GP";
                }
            }
            // POMERIGGIO
            if (gp.isSelected()) {
                if (g2.getSelectedItem().equals("Leggero")) {
                    pomeriggio+="GL";
                }else if(g2.getSelectedItem().equals("Medio")){
                    pomeriggio+="GM";
                }else if(g2.getSelectedItem().equals("Pesante")){
                    pomeriggio+="GP";
                }
            }
            // SERA
            if (gs.isSelected()) {
                if (g3.getSelectedItem().equals("Leggero")) {
                    sera+="GL";
                }else if(g3.getSelectedItem().equals("Medio")){
                    sera+="GM";
                }else if(g3.getSelectedItem().equals("Pesante")){
                    sera+="GP";
                }
            }
        }
        //*********************************************************************** VENERDI'
        if (giorni.contains("V")) {
        // MATTINA
            if (vm.isSelected()) {
                if (v1.getSelectedItem().equals("Leggero")) {
                    mattina+="VL";
                }else if(v1.getSelectedItem().equals("Medio")){
                    mattina+="VM";
                }else if(v1.getSelectedItem().equals("Pesante")){
                    mattina+="VP";
                }
            }
            // POMERIGGIO
            if (vp.isSelected()) {
                if (v2.getSelectedItem().equals("Leggero")) {
                    pomeriggio+="VL";
                }else if(v2.getSelectedItem().equals("Medio")){
                    pomeriggio+="VM";
                }else if(v2.getSelectedItem().equals("Pesante")){
                    pomeriggio+="VP";
                }
            }
            // SERA
            if (vs.isSelected()) {
                if (v3.getSelectedItem().equals("Leggero")) {
                    sera+="VL";
                }else if(v3.getSelectedItem().equals("Medio")){
                    sera+="VM";
                }else if(v3.getSelectedItem().equals("Pesante")){
                    sera+="VP";
                }
            }
        }
        //*********************************************************************** SABATO
        if (giorni.contains("S")) {
        // MATTINA
            if (sm.isSelected()) {
                if (s1.getSelectedItem().equals("Leggero")) {
                    mattina+="SL";
                }else if(s1.getSelectedItem().equals("Medio")){
                    mattina+="SM";
                }else if(s1.getSelectedItem().equals("Pesante")){
                    mattina+="SP";
                }
            }
            // POMERIGGIO
            if (sp.isSelected()) {
                if (s2.getSelectedItem().equals("Leggero")) {
                    pomeriggio+="SL";
                }else if(s2.getSelectedItem().equals("Medio")){
                    pomeriggio+="SM";
                }else if(s2.getSelectedItem().equals("Pesante")){
                    pomeriggio+="SP";
                }
            }
            // SERA
            if (ss.isSelected()) {
                if (s3.getSelectedItem().equals("Leggero")) {
                    sera+="SL";
                }else if(s3.getSelectedItem().equals("Medio")){
                    sera+="SM";
                }else if(s3.getSelectedItem().equals("Pesante")){
                    sera+="SP";
                }
            }
        }
        //*********************************************************************** DOMENICA
        if (giorni.contains("D")) {
            // MATTINA
            if (dm.isSelected()) {
                if (d1.getSelectedItem().equals("Leggero")) {
                    mattina+="DL";
                }else if(d1.getSelectedItem().equals("Medio")){
                    mattina+="DM";
                }else if(d1.getSelectedItem().equals("Pesante")){
                    mattina+="DP";
                }
            }
            // POMERIGGIO
            if (dp.isSelected()) {
                if (d2.getSelectedItem().equals("Leggero")) {
                    pomeriggio+="DL";
                }else if(d2.getSelectedItem().equals("Medio")){
                    pomeriggio+="DM";
                }else if(d2.getSelectedItem().equals("Pesante")){
                    pomeriggio+="DP";
                }
            }
            // SERA
            if (ds.isSelected()) {
                if (d3.getSelectedItem().equals("Leggero")) {
                    sera+="DL";
                }else if(d3.getSelectedItem().equals("Medio")){
                    sera+="DM";
                }else if(d3.getSelectedItem().equals("Pesante")){
                    sera+="DP";
                }
            }
        }  
        
        String giorniOre="";
            
        if (giorni.contains("L")) {
           giorniOre+="L";
        }
        if (giorni.contains("M")) {
           giorniOre+="M";
        }
        if (giorni.contains("W")) {
           giorniOre+="W";
        }
        if (giorni.contains("G")) {
           giorniOre+="G";
        }
        if (giorni.contains("V")) {
           giorniOre+="V";
        }
        if (giorni.contains("S")) {
           giorniOre+="S";
        }
        if (giorni.contains("D")) {
           giorniOre+="D";
        }
         
        Utente utente = new Utente();
        ScegliScheda scegli = new ScegliScheda(utente.getEmail(), parte,giorni, giorniOre, mattina, pomeriggio, sera, kcal, fabbisogno);
        scegli.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        SceltaAllenamento scheda = new SceltaAllenamento();
        scheda.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SceltaGiorni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SceltaGiorni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SceltaGiorni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SceltaGiorni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SceltaGiorni().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> d1;
    private javax.swing.JComboBox<String> d2;
    private javax.swing.JComboBox<String> d3;
    private javax.swing.JRadioButton dm;
    private javax.swing.JLabel domenica;
    private javax.swing.JRadioButton dp;
    private javax.swing.JRadioButton ds;
    private javax.swing.JComboBox<String> g1;
    private javax.swing.JComboBox<String> g2;
    private javax.swing.JComboBox<String> g3;
    private javax.swing.JLabel giovedi;
    private javax.swing.JRadioButton gm;
    private javax.swing.JRadioButton gp;
    private javax.swing.JRadioButton gs;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> l1;
    private javax.swing.JComboBox<String> l2;
    private javax.swing.JComboBox<String> l3;
    private javax.swing.JRadioButton lm;
    private javax.swing.JRadioButton lp;
    private javax.swing.JRadioButton ls;
    private javax.swing.JLabel lunedi;
    private javax.swing.JComboBox<String> m1;
    private javax.swing.JComboBox<String> m2;
    private javax.swing.JComboBox<String> m3;
    private javax.swing.JLabel martedi;
    private javax.swing.JLabel mercoledi;
    private javax.swing.JRadioButton mm;
    private javax.swing.JRadioButton mp;
    private javax.swing.JRadioButton ms;
    private javax.swing.JComboBox<String> s1;
    private javax.swing.JComboBox<String> s2;
    private javax.swing.JComboBox<String> s3;
    private javax.swing.JLabel sabato;
    private javax.swing.JRadioButton sm;
    private javax.swing.JRadioButton sp;
    private javax.swing.JRadioButton ss;
    private javax.swing.JComboBox<String> v1;
    private javax.swing.JComboBox<String> v2;
    private javax.swing.JComboBox<String> v3;
    private javax.swing.JLabel venerdi;
    private javax.swing.JRadioButton vm;
    private javax.swing.JRadioButton vp;
    private javax.swing.JRadioButton vs;
    private javax.swing.JComboBox<String> w1;
    private javax.swing.JComboBox<String> w2;
    private javax.swing.JComboBox<String> w3;
    private javax.swing.JRadioButton wm;
    private javax.swing.JRadioButton wp;
    private javax.swing.JRadioButton ws;
    // End of variables declaration//GEN-END:variables
}
