/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard_Admin;

import Autenticazione.Admin;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author giuse
 */
public class GestisciCorsi extends javax.swing.JFrame {
    private AggiornaCorso aggiorna;
    private CreaCorso crea;
    private Pannello_Admin pannelloAdmin;
    private Admin admin;
    private String nomecorso;
    
    public GestisciCorsi() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/imageicon.png");
        setIconImage(icon.getImage());
        setTitle("GYM FOR YOU");
        visualizzaRighe();
        this.nomecorso = nomecorso;
    }
    private void visualizzaRighe () {
        
        //METODO PER GESTIRE LA TABELLA
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        Df.setRowCount(0);

        //ISTANZIO L'OGGETTO CONTENENTE IL METODO CHE RITORNA LE RIGHE
        admin = new Admin();
        //CREO HASHMAP DATI
        Map dati = admin.mostra();
        
        //CICLA I TRAINER E I MEDICI CONTENTUTI NELL'HASHMAP
        for (int j=0; j<dati.size()/2; j++) {
           Vector v2 = new Vector();
           //CREA UNA VETTORE PER CIASCUN TRAINER E MEDICO
           for (int i = 1; i <= dati.size(); i++) {
                //AGGIUNGE L'EMAIL AL VETTORE
                v2.add(dati.get("Nome"+ j));
                //AGGIUNGE NOME AL VETTORE
                v2.add(dati.get("Trainer"+ j));
               
           }
           //AGGIUNGE LA RIGA ALLA TABELLA CONENTE IL VETTORE SOPRA
           Df.addRow(v2);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bottonecrea = new javax.swing.JButton();
        bottoneaggiorna1 = new javax.swing.JButton();
        bottoneelimina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 17, 30));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTISCI CORSI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 18), new java.awt.Color(255, 255, 102))); // NOI18N

        jTable1.setBackground(new java.awt.Color(255, 255, 102));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome corso", "Trainer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indietro1.png"))); // NOI18N
        jLabel1.setText("BACK");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        bottonecrea.setBackground(new java.awt.Color(255, 255, 102));
        bottonecrea.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        bottonecrea.setText("Crea nuovo corso");
        bottonecrea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottonecrea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottonecreaMouseClicked(evt);
            }
        });
        bottonecrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonecreaActionPerformed(evt);
            }
        });

        bottoneaggiorna1.setBackground(new java.awt.Color(255, 255, 102));
        bottoneaggiorna1.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        bottoneaggiorna1.setText("Aggiorna corso");
        bottoneaggiorna1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneaggiorna1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottoneaggiorna1MouseClicked(evt);
            }
        });
        bottoneaggiorna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneaggiorna1ActionPerformed(evt);
            }
        });

        bottoneelimina.setBackground(new java.awt.Color(255, 255, 102));
        bottoneelimina.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        bottoneelimina.setText("Elimina corso");
        bottoneelimina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneelimina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottoneeliminaMouseClicked(evt);
            }
        });
        bottoneelimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneeliminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bottoneaggiorna1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottonecrea)
                                .addGap(18, 18, 18)
                                .addComponent(bottoneelimina, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottoneaggiorna1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottonecrea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottoneelimina, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonecreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonecreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottonecreaActionPerformed

    private void bottoneaggiorna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneaggiorna1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottoneaggiorna1ActionPerformed

    private void bottoneeliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneeliminaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottoneeliminaActionPerformed

    private void bottoneaggiorna1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneaggiorna1MouseClicked
        // TODO add your handling code here:
        aggiorna = new AggiornaCorso(nomecorso);
        aggiorna.setVisible(true);
        dispose();
    }//GEN-LAST:event_bottoneaggiorna1MouseClicked

    private void bottonecreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonecreaMouseClicked
        // TODO add your handling code here:
        crea = new CreaCorso();
        crea.setVisible(true);
        dispose();
    }//GEN-LAST:event_bottonecreaMouseClicked

    private void bottoneeliminaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneeliminaMouseClicked
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Desideri confermare?", "", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            admin = new Admin();
            String msg = admin.eliminaCorso(nomecorso);
            if (msg.equals("Corso Eliminato!")) {
                JOptionPane.showMessageDialog(null, "Corso Eliminato Correttamente!", "Corso Eliminato!", JOptionPane.INFORMATION_MESSAGE);
                visualizzaRighe();
            }else{
                JOptionPane.showMessageDialog(null, "Corso non trovato opppure impossibile eliminare!", "Attenzione!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_bottoneeliminaMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        pannelloAdmin = new Pannello_Admin();
        pannelloAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // EVENTO CLICK JTABLE
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        //INDICE DELLA RIGA DELLA TABELLA
        int selectIndex = jTable1.getSelectedRow();
        nomecorso = Df.getValueAt(selectIndex,0).toString();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestisciCorsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestisciCorsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestisciCorsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestisciCorsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestisciCorsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneaggiorna1;
    private javax.swing.JButton bottonecrea;
    private javax.swing.JButton bottoneelimina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
