package Consultazioni.Trainer;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author giuse
 */
public class InviaRisposta extends javax.swing.JFrame {

    
    private VisualizzaDomande visualizza;
    
    private String id;
    private String domanda;
    private String risposta;
    
    public InviaRisposta(String id,String domanda, String risposta) {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/imageicon.png");
        setIconImage(icon.getImage());
        setTitle("GYM FOR YOU");
        this.id = id;
        this.domanda = domanda;
        this.risposta = risposta;
        
        campodomanda.setText(domanda);
        camporisposta.setText(risposta);
        
        if(!risposta.equals("")){
            inviarisposta.setVisible(false);
        }
    }

    private InviaRisposta() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campodomanda = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        camporisposta = new javax.swing.JTextArea();
        inviarisposta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 17, 30));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INVIA RISPOSTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 18), new java.awt.Color(255, 255, 102))); // NOI18N

        campodomanda.setEditable(false);
        campodomanda.setBackground(new java.awt.Color(155, 17, 30));
        campodomanda.setColumns(20);
        campodomanda.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        campodomanda.setLineWrap(true);
        campodomanda.setRows(5);
        campodomanda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N
        jScrollPane1.setViewportView(campodomanda);

        camporisposta.setBackground(new java.awt.Color(155, 17, 30));
        camporisposta.setColumns(20);
        camporisposta.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        camporisposta.setLineWrap(true);
        camporisposta.setRows(5);
        camporisposta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Risposta (Max 250 caratteri)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N
        jScrollPane2.setViewportView(camporisposta);

        inviarisposta.setBackground(new java.awt.Color(255, 255, 102));
        inviarisposta.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        inviarisposta.setText("INVIA RISPOSTA");
        inviarisposta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inviarisposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inviarispostaMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indietro1.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inviarisposta)
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inviarisposta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inviarispostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inviarispostaMouseClicked
        // TODO add your handling code here:
        MessaggiTrainer chat =  new MessaggiTrainer();
        String msg = chat.inviaRisposta(id, camporisposta.getText());
        
       if (msg.equals("Risposta inviata!")) {
            JOptionPane.showMessageDialog(null, "Risposta inviata!", "Risposta inviata", JOptionPane.INFORMATION_MESSAGE);
            visualizza = new VisualizzaDomande();
            visualizza.setVisible(true);
            dispose();
        }else if(msg.equals("Risposta non inviata")){
            JOptionPane.showMessageDialog(null, "Impossibile inviare la risposta!", "Risposta non inviata", JOptionPane.WARNING_MESSAGE);
        }else if(msg.equals("Risposta non inviata! La domanda contiene più di 250 caratteri!")){
            JOptionPane.showMessageDialog(null, "La risposta contiene più di 250 caratteri", "Attenzione!", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_inviarispostaMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        visualizza = new VisualizzaDomande();
        visualizza.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InviaRisposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InviaRisposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InviaRisposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InviaRisposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InviaRisposta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campodomanda;
    private javax.swing.JTextArea camporisposta;
    private javax.swing.JButton inviarisposta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
