package Dashboard_Utente;

import Autenticazione.Utente;
import Impostazioni.Xml;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Calcolo_MassaGra_MassaMag extends javax.swing.JFrame {
    private Utente utente;
    private Xml xml;
    
    public Calcolo_MassaGra_MassaMag() {
                       
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/imageicon.png");
        setIconImage(icon.getImage());
        setTitle("GYM FOR YOU");
        utente = new Utente();
        
       
        //SETTARE I TEXT FIELD CON I VALORI PRELEVATI DAL FILEXML.SAVE
        campovita.setText(Float.toString(utente.getCrf_vita()));
        campofianchi.setText(Float.toString(utente.getCrf_fianchi()));
        campocollo.setText(Float.toString(utente.getCrf_collo()));
        campomassamagra.setEditable(false);
        campoaltezza.setText(utente.getAltezza() + "  CM");
        campopeso.setText(utente.getPeso() + "  KG");
        //
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        campomassamagra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoaltezza = new javax.swing.JLabel();
        campopeso = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        circonferenza_vita = new javax.swing.JLabel();
        circonferenza_fianchi = new javax.swing.JLabel();
        circonferenza_collo = new javax.swing.JLabel();
        campovita = new javax.swing.JTextField();
        campofianchi = new javax.swing.JTextField();
        campocollo = new javax.swing.JTextField();
        bottone_calcola = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 17, 30));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CALCOLO MASSA GRASSA E MASSA MAGRA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(155, 17, 30));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Qui puoi ussufruire di un calcolatore che ti permette di calcolare la massa grassa e la massa \nmagra  del tuo corpo. \nLa massa grassa è importante per capire in che stato si trova il tuo corpo. Per questo una volta \nottenuto il risultato puoi confrontarlo con la tabella che  mettiamo a tua disposizione  e\ncomprendere lo stato del tuo corpo. ");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Massa magra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 12))); // NOI18N

        jButton1.setBackground(new java.awt.Color(155, 17, 30));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jButton1.setText("Calcola massa magra");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        campomassamagra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campomassamagraActionPerformed(evt);
            }
        });

        jLabel1.setText("ALTEZZA");

        jLabel2.setText("PESO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(campomassamagra))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoaltezza, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campopeso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campopeso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoaltezza, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campomassamagra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Massa grassa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 12))); // NOI18N

        circonferenza_vita.setFont(new java.awt.Font("Yu Gothic UI", 3, 11)); // NOI18N
        circonferenza_vita.setText("Circonferenza vita");

        circonferenza_fianchi.setFont(new java.awt.Font("Yu Gothic UI", 3, 11)); // NOI18N
        circonferenza_fianchi.setText("Circonferenza fianchi");

        circonferenza_collo.setFont(new java.awt.Font("Yu Gothic UI", 3, 11)); // NOI18N
        circonferenza_collo.setText("Circonferenza collo");

        campovita.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        campovita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campovitaActionPerformed(evt);
            }
        });

        campofianchi.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N

        campocollo.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N

        bottone_calcola.setBackground(new java.awt.Color(155, 17, 30));
        bottone_calcola.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        bottone_calcola.setText("Calcola massa grassa");
        bottone_calcola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottone_calcolaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(circonferenza_vita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campovita, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(circonferenza_collo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campocollo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(circonferenza_fianchi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campofianchi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(bottone_calcola, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(circonferenza_vita, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campovita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circonferenza_fianchi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campofianchi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circonferenza_collo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campocollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottone_calcola, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setBackground(new java.awt.Color(255, 255, 102));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Peso minimo", "2%-4%", "10%-12%"},
                {"Forma atletica", "6%-13%", "14%-20%"},
                {"Buono stato di fitness", "14%-17%", "21%-24%"},
                {"Sopra della media", "18%-25%", "25%-31%"},
                {"Obesità", ">= di 26%", ">= del 32%"}
            },
            new String [] {
                "VALUTAZIONE", "UOMINI", "DONNE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indietro1.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(124, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campovitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campovitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campovitaActionPerformed

    private void bottone_calcolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottone_calcolaMouseClicked
        
        // BOTTONE CALCOLA MASSA GRASSA
        float vita = Float.parseFloat(campovita.getText().replace(",", "."));
        float fianchi = Float.parseFloat(campofianchi.getText().replace(",", "."));
        float collo = Float.parseFloat(campocollo.getText().replace(",", "."));
        
        
        if (vita >0 && fianchi >0 && collo >0) {
            
            utente = new Utente();
            // RICHIAMO IL METODO DELLA CLASSE CALCOLOMASSAGRASSA E PASSO I PARAMETRI PRELEVATI DAL TEXT FIELD
            double massaG = utente.formulaMassaGrassa(vita,fianchi,collo); 

            //METODO PER MODIFICARE VALORI CIRCONFERENZA ALL'INTERNO DELLA TABELLA UTENTE DEL DB
            String msg = utente.salvaCirconferenze( campovita.getText().replace(",", "."),
                                                    campofianchi.getText().replace(",", "."),
                                                    campocollo.getText().replace(",", "."),
                                                    Double.toString(massaG));

            //SALVARE DATI INSERITI IN INPUT NEL FILE XML
            xml = new Xml();
            xml.scriviXmlDati(utente.getEmail());
            //

            //CONFRONTO IL MESSAGGIO RESTITUITO DAL SERVER CON QUELLO SOTTO
            if(msg.equals("Circonferenze Modificate")){

                //NASCONDI TEXT FIELD E LABEL E MOSTRA IL RISULTATO DELLA MASSA GRASSA         
                circonferenza_vita.setVisible(false);
                circonferenza_fianchi.setVisible(false);
                campovita.setVisible(false);
                campofianchi.setVisible(false);

                circonferenza_collo.setText("RISULTATO:   ");
                campocollo.setEditable(false);
                campocollo.setText("%  "+String.format("%.2f", massaG));

            }else if(msg.equals("Modifiche Fallite")){
                JOptionPane.showMessageDialog(null, "Inserire Valori", "Attenzione", JOptionPane.WARNING_MESSAGE);
            }
            
        }else if (campovita.getText().equals("") && campofianchi.getText().equals("") && campocollo.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Impossibile inserire valori pari a 0.", "Attenzione", JOptionPane.WARNING_MESSAGE);
        }else if (vita<=0 && fianchi <=0 && collo <=0){
            JOptionPane.showMessageDialog(null, "Impossibile inserire valori negativi o pari a 0.", "Attenzione", JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Impossibile inserire i valori.", "Attenzione", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bottone_calcolaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // CALCOLO MASSA MAGRA
        // RICHIAMO IL METODO DELLA CLASSE UTENTE
        utente = new Utente();  //--> NUOVA ISTANZA PERCHE' VA FATTA QUANDO SERVE E NON IN GENERALE
        double massaM = utente.formulaMassaMagra();
        campomassamagra.setText("Kg  "+String.format("%.2f", massaM));
        
        //CAST VARIABILE DOUBLE IN STRING
        String massa_magra = Double.toString(massaM);
        //RICHIAMO IL METODO DELLA CLASSE UTENTE PER INSERIRE LA MASSA MAGRA NEL DB
        String msg = utente.inserisciMassaMagra(massa_magra);
        if(msg.equals("Massa Magra Inserita")){
            //SCRIVI IL FILEXML.SAVE
            xml = new Xml();
            xml.scriviXmlDati(utente.getEmail());
        }
            
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void campomassamagraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campomassamagraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campomassamagraActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //BOTTONE INDIETRO
        Pannello_Utente pannello = new Pannello_Utente();
        pannello.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcolo_MassaGra_MassaMag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcolo_MassaGra_MassaMag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcolo_MassaGra_MassaMag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcolo_MassaGra_MassaMag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calcolo_MassaGra_MassaMag().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottone_calcola;
    private javax.swing.JLabel campoaltezza;
    private javax.swing.JTextField campocollo;
    private javax.swing.JTextField campofianchi;
    private javax.swing.JTextField campomassamagra;
    private javax.swing.JLabel campopeso;
    private javax.swing.JTextField campovita;
    private javax.swing.JLabel circonferenza_collo;
    private javax.swing.JLabel circonferenza_fianchi;
    private javax.swing.JLabel circonferenza_vita;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
