package Dashboard_Utente;

import Autenticazione.Utente;
import Impostazioni.Xml;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;


public class CompilaQuestionario extends javax.swing.JFrame {
    
    private Pannello_Utente pannello;
    
    public CompilaQuestionario() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/imageicon.png");
        setIconImage(icon.getImage());
        setTitle("GYM FOR YOU");
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane4.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane5.getVerticalScrollBar().setUnitIncrement(16);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        d1si = new javax.swing.JRadioButton();
        d1no = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        d2si = new javax.swing.JRadioButton();
        d2no = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        d3si = new javax.swing.JRadioButton();
        d3no = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        d4si = new javax.swing.JRadioButton();
        d4no = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        d5si = new javax.swing.JRadioButton();
        d5no = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        d6si = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        d7si = new javax.swing.JRadioButton();
        d6no = new javax.swing.JRadioButton();
        d7no = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        d8si = new javax.swing.JRadioButton();
        d8no = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        d9si = new javax.swing.JRadioButton();
        d9no = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        d10si = new javax.swing.JRadioButton();
        d10no = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        d11si = new javax.swing.JRadioButton();
        d11no = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        d12si = new javax.swing.JRadioButton();
        d12no = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        d13si = new javax.swing.JRadioButton();
        d13no = new javax.swing.JRadioButton();
        bottoneinvia = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(155, 17, 30));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("hai problemi alle ossa o alle articolazioni (per esempio schiena, anche ginocchia) che potrebbero peggiorare \na causa dell'attività fisica? ");
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setSelectionColor(new java.awt.Color(155, 17, 30));
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(155, 17, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(155, 17, 30));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUESTIONARIO UTENTE ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(155, 17, 30));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel1.setText("Provi dolore al torace quando fai attività fisica?");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d1si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup1.add(d1si);
        d1si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d1si.setForeground(new java.awt.Color(255, 255, 102));
        d1si.setText("Sì");
        d1si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d1si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1siActionPerformed(evt);
            }
        });

        d1no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup1.add(d1no);
        d1no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d1no.setForeground(new java.awt.Color(255, 255, 102));
        d1no.setText("No");
        d1no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d1no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1noActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(155, 17, 30));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel2.setText("Provi vertigini o giramenti di testa prima o dopo aver fatto attività fisica?");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d2si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup2.add(d2si);
        d2si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d2si.setForeground(new java.awt.Color(255, 255, 102));
        d2si.setText("Sì");
        d2si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d2no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup2.add(d2no);
        d2no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d2no.setForeground(new java.awt.Color(255, 255, 102));
        d2no.setText("No");
        d2no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(155, 17, 30));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Hai problemi alle ossa o alle articolazioni (per esempio schiena, anche ginocchia) che potrebbero peggiorare \na causa dell'attività fisica? ");
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea2.setSelectionColor(new java.awt.Color(155, 17, 30));
        jScrollPane3.setViewportView(jTextArea2);

        d3si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup3.add(d3si);
        d3si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d3si.setForeground(new java.awt.Color(255, 255, 102));
        d3si.setText("Sì");
        d3si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d3si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3siActionPerformed(evt);
            }
        });

        d3no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup3.add(d3no);
        d3no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d3no.setForeground(new java.awt.Color(255, 255, 102));
        d3no.setText("No");
        d3no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d3no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3noActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(155, 17, 30));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel3.setText("Hai mai avuto perdita dei sensi o quasi perdita dei sensi durante o dopo l'esercizio fisico?");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d4si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup4.add(d4si);
        d4si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d4si.setForeground(new java.awt.Color(255, 255, 102));
        d4si.setText("Sì");
        d4si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d4si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4siActionPerformed(evt);
            }
        });

        d4no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup4.add(d4no);
        d4no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d4no.setForeground(new java.awt.Color(255, 255, 102));
        d4no.setText("No");
        d4no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d4no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4noActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(155, 17, 30));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel4.setText("Hai mai avuto problemi respiratori durante o dopo lo sforzo fisico");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d5si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup5.add(d5si);
        d5si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d5si.setForeground(new java.awt.Color(255, 255, 102));
        d5si.setText("Sì");
        d5si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d5no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup5.add(d5no);
        d5no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d5no.setForeground(new java.awt.Color(255, 255, 102));
        d5no.setText("No");
        d5no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setBackground(new java.awt.Color(155, 17, 30));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel5.setText("Hai mai avuto un battito cardiaco troppo accelerato non correlato all'esercizio fisico?");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 6", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d6si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup6.add(d6si);
        d6si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d6si.setForeground(new java.awt.Color(255, 255, 102));
        d6si.setText("Sì");
        d6si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(155, 17, 30));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Un medico ti  ha mai detto che hai un qualsiasi problema cardiaco, pressione arteriosa alta, colesterolo alto, un\nsoffio al cuore, un'aritmia cardiaca, un infezione al cuore nell'ultimo mese, una crisi convulsiva inspiegata, febbre \nreumatica oppure ti ha mai detto che devi fare solo attività fisica raccomandata da egli stesso?");
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 7", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N
        jScrollPane4.setViewportView(jTextArea3);

        d7si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup7.add(d7si);
        d7si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d7si.setForeground(new java.awt.Color(255, 255, 102));
        d7si.setText("Sì");
        d7si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d6no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup6.add(d6no);
        d6no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d6no.setForeground(new java.awt.Color(255, 255, 102));
        d6no.setText("No");
        d6no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d7no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup7.add(d7no);
        d7no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d7no.setForeground(new java.awt.Color(255, 255, 102));
        d7no.setText("No");
        d7no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d7no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d7noActionPerformed(evt);
            }
        });

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(155, 17, 30));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Un medico ti  ha mai detto che hai asma, crisi convulsive, epilessia, problemi di salute che impediscono lo sport, \ndiabete, obesità, malattie ortopediche, malattie neurologiche, malattie respiratorie?");
        jTextArea4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 8", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N
        jScrollPane5.setViewportView(jTextArea4);

        d8si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup8.add(d8si);
        d8si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d8si.setForeground(new java.awt.Color(255, 255, 102));
        d8si.setText("Sì  ");
        d8si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d8no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup8.add(d8no);
        d8no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d8no.setForeground(new java.awt.Color(255, 255, 102));
        d8no.setText("No ");
        d8no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setBackground(new java.awt.Color(155, 17, 30));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel6.setText("Hai qualche allergia per esempio pollini polvere, cibi ecc? ");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 10", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d9si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup9.add(d9si);
        d9si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d9si.setForeground(new java.awt.Color(255, 255, 102));
        d9si.setText("Sì");
        d9si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d9no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup9.add(d9no);
        d9no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d9no.setForeground(new java.awt.Color(255, 255, 102));
        d9no.setText("No");
        d9no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setBackground(new java.awt.Color(155, 17, 30));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel7.setText("Un medico ti ha prescitto un test per il cuore ECG, Holter o ECO?");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 9", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d10si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup10.add(d10si);
        d10si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d10si.setForeground(new java.awt.Color(255, 255, 102));
        d10si.setText("Sì");
        d10si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d10no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup10.add(d10no);
        d10no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d10no.setForeground(new java.awt.Color(255, 255, 102));
        d10no.setText("No");
        d10no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d10no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d10noActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(155, 17, 30));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel8.setText("Negli ultimi due anni hai preso farmaci in maniera costante?");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 13", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        d11si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup11.add(d11si);
        d11si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d11si.setForeground(new java.awt.Color(255, 255, 102));
        d11si.setText("Sì");
        d11si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d11no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup11.add(d11no);
        d11no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d11no.setForeground(new java.awt.Color(255, 255, 102));
        d11no.setText("No");
        d11no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setBackground(new java.awt.Color(155, 17, 30));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel9.setText("Hai mai avuto arrossamenti orticaria o eruzioni cutanee durante o dopo l'esercizio fisico?");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 11", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d12si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup12.add(d12si);
        d12si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d12si.setForeground(new java.awt.Color(255, 255, 102));
        d12si.setText("Sì");
        d12si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d12no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup12.add(d12no);
        d12no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d12no.setForeground(new java.awt.Color(255, 255, 102));
        d12no.setText("No");
        d12no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setBackground(new java.awt.Color(155, 17, 30));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel10.setText("Attualmente stai facendo cure, usando farmaci (qualsiasi tipo) su prescrizione medica o da banco?");
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domanda 12", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 14), new java.awt.Color(255, 255, 102))); // NOI18N

        d13si.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup13.add(d13si);
        d13si.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d13si.setForeground(new java.awt.Color(255, 255, 102));
        d13si.setText("Sì");
        d13si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        d13no.setBackground(new java.awt.Color(155, 17, 30));
        buttonGroup13.add(d13no);
        d13no.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        d13no.setForeground(new java.awt.Color(255, 255, 102));
        d13no.setText("No");
        d13no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bottoneinvia.setBackground(new java.awt.Color(255, 255, 102));
        bottoneinvia.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        bottoneinvia.setForeground(new java.awt.Color(155, 17, 30));
        bottoneinvia.setText("INVIA");
        bottoneinvia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneinvia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottoneinviaMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indietro1.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d8si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d8no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d9si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d9no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d10si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d10no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d11si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d11no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d12si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d12no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bottoneinvia, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d2si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d2no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d3si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d3no, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d1si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d1no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d5si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d5no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d4si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d4no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d6si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d6no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d7si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(d7no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d13si, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(d13no, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1si)
                    .addComponent(d1no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d2si, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d3si, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3no, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d4no, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4si, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d5si, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d5no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(d6si, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(d6no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d7si, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d7no, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d8si)
                    .addComponent(d8no))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d9si)
                    .addComponent(d9no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d10si)
                    .addComponent(d10no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d11si)
                    .addComponent(d11no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d12si)
                    .addComponent(d12no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d13si)
                    .addComponent(d13no))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bottoneinvia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void d4noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d4noActionPerformed

    private void d4siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d4siActionPerformed

    private void d1noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1noActionPerformed

    private void d1siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1siActionPerformed

    private void d3siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d3siActionPerformed

    private void d3noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d3noActionPerformed

    private void d10noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d10noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d10noActionPerformed

    private void bottoneinviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneinviaMouseClicked
        
        JRadioButton[] jradioSi = new JRadioButton[]{d1si,d2si,d3si,d4si,d5si,d6si,d7si,d8si,d9si,d10si,d11si,d12si,d13si};
        JRadioButton[] jradioNo = new JRadioButton[]{d1no,d2no,d3no,d4no,d5no,d6no,d7no,d8no,d9no,d10no,d11no,d12no,d13no};
        
        Map risposte = new HashMap();
        for (int i = 0; i < jradioSi.length; i++) {
            if (jradioSi[i].isSelected()) {
                risposte.put("d"+i, "si");
            }else if (jradioNo[i].isSelected()){
                risposte.put("d"+i, "no");
            }
        }
            
        Utente utente = new Utente();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Desideri confermare?", "", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){

            // RICHIAMO IL METODO DELLA CLASSE QUESTIONARIO E PASSO I PARAMETRI PRELEVATI DAI RADIO BUTTON
            String msg = utente.invia(utente.getEmail(),(String)risposte.get("d0"),(String)risposte.get("d1"),(String)risposte.get("d2"),(String)risposte.get("d3"),
                                     (String)risposte.get("d4"),(String)risposte.get("d5"),(String)risposte.get("d6"),(String)risposte.get("d7"),(String)risposte.get("d8"),
                                     (String)risposte.get("d9"),(String)risposte.get("d10"),(String)risposte.get("d11"),(String)risposte.get("d12"));
            
            //CONFRONTO IL MESSAGGIO RESTITUITO DAL SERVER CON QUELLO SOTTO
            if (msg.equals("Dati inviati")) {

                //SCRIVO FILEXML.SAVE CON I VALORI PRELEVATI DAL DB
                Xml xml = new Xml();
                xml.scriviXmlDati(utente.getEmail());
                //
               JOptionPane.showMessageDialog(null, "Questionario inviato con successo!", "QUESTIONARIO INVIATO", JOptionPane.INFORMATION_MESSAGE);
               dispose();
               pannello = new Pannello_Utente();
               pannello.setVisible(true);

            }else if (msg.equals("Campi vuoti")){
                JOptionPane.showMessageDialog(null, "Una o più domande risultano senza risposta!", "Attenzione", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_bottoneinviaMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        //BOTTONE INDIETRO
        pannello = new Pannello_Utente();
        pannello.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void d7noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d7noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d7noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompilaQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompilaQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompilaQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompilaQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CompilaQuestionario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneinvia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton d10no;
    private javax.swing.JRadioButton d10si;
    private javax.swing.JRadioButton d11no;
    private javax.swing.JRadioButton d11si;
    private javax.swing.JRadioButton d12no;
    private javax.swing.JRadioButton d12si;
    private javax.swing.JRadioButton d13no;
    private javax.swing.JRadioButton d13si;
    private javax.swing.JRadioButton d1no;
    private javax.swing.JRadioButton d1si;
    private javax.swing.JRadioButton d2no;
    private javax.swing.JRadioButton d2si;
    private javax.swing.JRadioButton d3no;
    private javax.swing.JRadioButton d3si;
    private javax.swing.JRadioButton d4no;
    private javax.swing.JRadioButton d4si;
    private javax.swing.JRadioButton d5no;
    private javax.swing.JRadioButton d5si;
    private javax.swing.JRadioButton d6no;
    private javax.swing.JRadioButton d6si;
    private javax.swing.JRadioButton d7no;
    private javax.swing.JRadioButton d7si;
    private javax.swing.JRadioButton d8no;
    private javax.swing.JRadioButton d8si;
    private javax.swing.JRadioButton d9no;
    private javax.swing.JRadioButton d9si;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
