package Consultazioni.Utente;

import Dashboard_Utente.Pannello_Utente;
import javax.swing.ImageIcon;

public class SceltaOperazioni extends javax.swing.JFrame {
    
    private String type;
    
    public SceltaOperazioni(String type) {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/imageicon.png");
        setIconImage(icon.getImage());
        setTitle("GYM FOR YOU");
        this.type = type;
        if (type.equals("trn")) {
            bottoneRecensisci.setText("Recensisci trainer");
            bottoneInvia.setText("Invia domanda al trainer");
        }
    }

    private SceltaOperazioni() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bottoneRecensisci = new javax.swing.JButton();
        bottoneInvia = new javax.swing.JButton();
        bottoneVisualizza = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 17, 30));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SCEGLI OPERAZIONE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 3, 18), new java.awt.Color(255, 255, 102))); // NOI18N

        bottoneRecensisci.setBackground(new java.awt.Color(255, 255, 102));
        bottoneRecensisci.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        bottoneRecensisci.setForeground(new java.awt.Color(155, 17, 30));
        bottoneRecensisci.setText("Recensisci medico");
        bottoneRecensisci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneRecensisci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottoneRecensisciMouseClicked(evt);
            }
        });

        bottoneInvia.setBackground(new java.awt.Color(255, 255, 102));
        bottoneInvia.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        bottoneInvia.setForeground(new java.awt.Color(155, 17, 30));
        bottoneInvia.setText("Invia domanda al medico");
        bottoneInvia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneInvia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottoneInviaMouseClicked(evt);
            }
        });

        bottoneVisualizza.setBackground(new java.awt.Color(255, 255, 102));
        bottoneVisualizza.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        bottoneVisualizza.setForeground(new java.awt.Color(155, 17, 30));
        bottoneVisualizza.setText("Visualizza e valuta risposte");
        bottoneVisualizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneVisualizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottoneVisualizzaMouseClicked(evt);
            }
        });
        bottoneVisualizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneVisualizzaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indietro1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bottoneVisualizza, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottoneInvia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottoneRecensisci, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(bottoneInvia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(bottoneVisualizza, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(bottoneRecensisci, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneVisualizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneVisualizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottoneVisualizzaActionPerformed

    private void bottoneInviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneInviaMouseClicked
        // TODO add your handling code here:
        InviaDomanda invia;
        if (type.equals("trn")) {
            invia = new InviaDomanda("trn");
            invia.setVisible(true);
            dispose();
        }else if(type.equals("med")){
            invia = new InviaDomanda("med");
            invia.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_bottoneInviaMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Pannello_Utente pannello = new Pannello_Utente();
        pannello.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void bottoneVisualizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneVisualizzaMouseClicked
        // TODO add your handling code here:
        VisualizzaDomandeRisposte visualizza;
        if (type.equals("trn")) {
            visualizza  = new VisualizzaDomandeRisposte("trn");
            visualizza.setVisible(true);
            dispose();
        }else if(type.equals("med")){
            visualizza = new VisualizzaDomandeRisposte("med");
            visualizza.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_bottoneVisualizzaMouseClicked

    private void bottoneRecensisciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneRecensisciMouseClicked
        // TODO add your handling code here:
        Valuta recensisci;
        if (type.equals("trn")) {
            recensisci = new Valuta("trn");
            recensisci.setVisible(true);
            dispose();
        }else if(type.equals("med")){
            recensisci = new Valuta("med");
            recensisci.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_bottoneRecensisciMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SceltaOperazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SceltaOperazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SceltaOperazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SceltaOperazioni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SceltaOperazioni().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneInvia;
    private javax.swing.JButton bottoneRecensisci;
    private javax.swing.JButton bottoneVisualizza;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
